version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=117022657282.dkr.ecr.us-east-1.amazonaws.com/resumeappecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t resumeappecr .
      - docker tag resumeappecr:latest 117022657282.dkr.ecr.us-east-1.amazonaws.com/resumeappecr:latest

artifacts:
    files: imagedefinitions.json
